[project]
name = "ping-pong-measurer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "eclipse-zenoh>=1.3.4",
    "hbmqtt==0.9.5",
    "paho-mqtt==1.6.1",
    "setuptools>=75.3.2",
    "websockets==8.1",
]
